---
abstract: 'uses mmap to map in a file as a Perl variable'
author:
  - 'Scott Walters <swalters@cpan.org>'
build_requires:
  Errno: '0'
  ExtUtils::MakeMaker: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.94, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Sys-Mmap
no_index:
  directory:
    - t
    - inc
requires:
  DynaLoader: '0'
  Test::More: '0'
  XSLoader: '0'
resources:
  bugtracker: https://github.com/toddr/Sys-Mmap/issues
  license: http://dev.perl.org/licenses/
  repository: http://github.com/toddr/Sys-Mmap/tree/master
version: 0.17_01
